### PR TITLE
Feature/default variables

### PR DESCRIPTION
**Pull request by laurenskling**
Created some extra code (after #5 ),
I want to set some default values for my templated emails. This looks like a easy way to me.

### CODE REVIEW

**Comment by ScottAgirs** [comment]
Hey @laurenskling thanks for the PR, if we can finalize #5 , I think this will be good for a merge too

**Comment by ScottAgirs** [comment]
@laurenskling if we could update this with the latest `master` changes, will merge this in too 🙌🏼

**Comment by laurenskling** [comment]
I've rebased the PR

**Review by ScottAgirs — APPROVED** [review]
LGTM, thanks @laurenskling

**Comment by laurenskling** [comment]
Thanks mate. Would you be so kind to release a version?

**Comment by ScottAgirs** [comment]
Hey @laurenskling sorry for the delay - holidays, eh, haha. 🎄 🥳 

Released [v3.4.1](https://github.com/ijsto/strapi-provider-email-postmark/releases/tag/v3.4.1)

**Pull request merged**
