### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by laurenskling**
I want to send a template, we need to support a different function on the client.

This is just an example; If you want to use a different code style.

I'm also not 100% sure this will not throw errors, I didn't test this code. I guess removeUndefined will filter out unused properties for the current situation right?

### CODE REVIEW

**Comment by laurenskling** [comment]
https://github.com/wildbit/postmark.js/wiki/Templates

**Review by ScottAgirs — COMMENTED** [review]
hey @laurenskling thank you for the PR, LGTM, I will review in more depth before tomorrow

**Comment by laurenskling** [comment]
Thanks mate

**Comment by ScottAgirs** [comment]
@laurenskling merged in. If you have a second please add simple code samples to README. And if you do - please don't spend too much time on it - API is likely to change with the next MINOR release.

Thank you for the PR.

**Pull request merged**
