### PR TITLE
Upgrade to strapi@4.0.0

### PR DESCRIPTION
**Pull request by dostuffthatmatters**
The config is different in v4: See updated README.
I also upgraded to the newest postmark `2.x.x` library.

Best,
Moritz

### CODE REVIEW

**Review by ScottAgirs — APPROVED** [review]
LGTM, thank you @dostuffthatmatters

**Comment by dostuffthatmatters** [comment]
Great! It would be good to have a release `4.0.0` so that people can install this version of the package.

Best,
Moritz

**Comment by laurenskling** [comment]
Hey @ScottAgirs, I'm in the process of migrating to strapi 4. Can you make a release out of this? Thanks mate

**Comment by laurenskling** [comment]
Any change @ScottAgirs ? If you are not interested in the package anymore, you could make me maintainer

**Comment by ScottAgirs** [comment]
> Any change @ScottAgirs ? If you are not interested in the package anymore, you could make me maintainer

Hey @laurenskling sorry for the delays, have severely limited bandwidth atm, heh. Definitely still interested, but also more than happy to open doors for you as a maintainer (and anyone else for that matter)!

**Comment by laurenskling** [comment]
Thanks mate. Although to release 4.0.0 I would need access on NPM as well. I don't know how that works, is that something you can share?

**Comment by ScottAgirs** [comment]
@laurenskling let's move this to [Twitter](https://twitter.com/scottagirs) or [Discord](https://discord.gg/GrdX6jRnFH)?

**Comment by laurenskling** [comment]
@ScottAgirs I tried messaging you on Discord, no response :)

**Pull request merged**
